import React, { useEffect } from "react";
import Head from "next/head";
import Lottie from "lottie-react";
import patternAnimation from "../js/lottie/homepage.json";
import Footer from "../components/Footer";
import CategorySlider from "../components/CategorySlider";
import VerticalScrollElementLayout from "../components/VerticalScrollElementLayout";
import ReactFullpage from "@fullpage/react-fullpage";
export default function Home() {
  useEffect(() => {
    document.body.setAttribute("titles", "Home");

   
  }, []);

  return (
    <ReactFullpage
      onLeave={(origin, destination, direction) => {
        console.log("on leave event", destination);
      }}
      responsiveWidth={800}
      render={({ state, fullpageApi }) => {
        if (fullpageApi?.getScrollY() > 100) {
          typeof window != "undefined" && document.getElementById("fullpage")?.classList?.add("bottom-0");
        } else {
          typeof window != "undefined" && document.getElementById("fullpage")?.classList?.remove("bottom-0");
        }

        return (
          <VerticalScrollElementLayout>
            <Head>
              <title>Home</title>
              <meta name="description" content="Generated by create next app" />
              <link
                rel="stylesheet"
                type="text/css"
                href="https://unpkg.com/fullpage.js@3.0.1/dist/fullpage.min.css"
              />
            </Head>
            <section
              id="section-1"
              data-theme="white"
              className="section hero main"
            >
               <div className="fixed-gradient"></div>
              <div className="container">
                <div className="row align-items-center">
                  <div className="col-md-12">
                    <div className="row">
                      <div className="col-md-10">
                        <div className="hero-content">
                          <h5>Build.Better.Tech </h5>
                          <h1>
                            {" "}
                            A Soft{" "}
                            <span className="text-bg">
                              War
                              <span className="text-brand">
                                <span className="rotate-30">e</span>
                              </span>
                              house
                            </span>{" "}
                            That Grows With Your Business
                          </h1>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            <section
              id="section-2"
              data-theme="black"
              className="section bg-dark  main-md  work-section section"
            >
              <div className="container">
                <div className="">
                  <div class="abs-slider-item">
                    <CategorySlider />
                  </div>
                </div>
              </div>
            </section>

            <section
              id="section-3"
              data-theme="black"
              className="section bg-dark  main  work-section"
            >
              <div className="container">
                <div className="row  align-items-center">
                  <div className="col-md-12">
                    <div className="row mb-5  mt-5">
                      <div className="col-md-10">
                        <h2>
                          We d
                          <span className="text-brand">
                            <span className="rotate-30 movetext">e</span>
                          </span>
                          sign better software solutions to build and grow your
                          API driven business.
                        </h2>
                      </div>
                    </div>

                    <div className="row mt-5">
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img src="img/icons/api.svg" alt="api" />
                          <h4> API's</h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img
                            src="img/icons/monolith-microservices.svg"
                            alt="api"
                          />
                          <h4> Monolith to Microservices</h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img src="img/icons/mvp.svg" alt="api" />
                          <h4> MVP</h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img src="img/icons/web-app.svg" alt="api" />
                          <h4> Web Application</h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img src="img/icons/maintainance.svg" alt="api" />
                          <h4> Maintainance</h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img
                            src="img/icons/business-automation.svg"
                            alt="api"
                          />
                          <h4> Business Automation </h4>
                        </div>
                      </div>
                      <div className="col-md-3 col-6">
                        <div className="service-list text-center">
                          <img
                            src="img/icons/mobile-application.svg"
                            alt="api"
                          />
                          <h4> Mobile App </h4>
                        </div>
                      </div>
                      <div className="col-md-3  col-6">
                        <div className="service-list text-center">
                          <img src="img/icons/cloud-services.svg" alt="api" />
                          <h4> Cloud Services </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            <section
              id="section-4"
              data-theme="white"
              className="section main function-section"
            >
              <div className="container">
                <div className="row  align-items-center">
                  <div className="col-md-12">
                    <div className="row mb-5">
                      <div className="col-md-10">
                        <h2 className="m-0">
                          We start d
                          <span className="text-brand">
                            <span className="rotate-30">e</span>
                          </span>
                          velopment from the minimum necessary functions instead
                          of making it all at once.
                        </h2>
                      </div>
                    </div>

                    <div className="row mt-5">
                      <div className="col-md-6">
                        <div className="fixed-content lottie-sm">
                          <Lottie
                            animationData={patternAnimation}
                            background=""
                            speed="1"
                            loop
                            autoplay
                          ></Lottie>
                        </div>
                      </div>

                      <div className="col-md-6">
                        <div className="function-list">
                          <div className="function-item">
                            <h5>
                              {" "}
                              <span className="text-brand">L</span>aunch a MVP
                            </h5>
                            <p>
                              {" "}
                              We create a business model for your growth. Only
                              focus on making things that generate the outcomes
                              that we want.
                            </p>
                          </div>
                          <div className="function-item">
                            <h5>
                              {" "}
                              <span className="text-brand">E</span>mpathize your
                              users{" "}
                            </h5>
                            <p>
                              {" "}
                              We bring the true nature of a product to life
                              faster, in a collaborative, cross-functional and
                              user centric way.
                            </p>
                          </div>
                          <div className="function-item">
                            <h5>
                              {" "}
                              <span className="text-brand">A</span>utomate your
                              service delivery{" "}
                            </h5>
                            <p>
                              {" "}
                              Improve disciplines to achieve both speed and
                              direction towards its strategic goal.
                            </p>
                          </div>
                          <div className="function-item">
                            <h5>
                              {" "}
                              i<span className="text-brand">N</span>novate and
                              grow{" "}
                            </h5>
                            <p> Keep growing with LEAN.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            <section
              id="section-5"
              data-theme="white"
              className="section main clients-section"
            >
              <div className="container">
                <div className="row  align-items-center">
                  <div className="col-md-12">
                    <div className="row mb-5">
                      <div className="col-md-10">
                        <h2 className="m-0">
                          Our cli
                          <span className="text-brand">
                            <span className="rotate-30">e</span>
                          </span>
                          nts and collaborators. Our fascination for innovation
                          is mutual. We pride on our enthusiasm to do more.
                        </h2>
                      </div>
                    </div>

                    <div className="row mt-5 justify-content-center">
                      <div className="col-md-3 col-4">
                        <div className="client-logo">
                          <img
                            src="img/clients/ontraport.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-center">
                          <img
                            src="img/clients/kintone.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>

                      <div className="col-md-3 col-4">
                        <div className="client-logo  text-center">
                          <img
                            src="img/clients/mongodb.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-end">
                          <img
                            src="img/clients/figma.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo">
                          <img
                            src="img/clients/aws.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-center">
                          <img
                            src="img/clients/java.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-center">
                          <img
                            src="img/clients/adobe.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-end">
                          <img
                            src="img/clients/strapi.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo">
                          <img
                            src="img/clients/js.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-center">
                          <img
                            src="img/clients/mysql.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-center">
                          <img
                            src="img/clients/wordpress.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                      <div className="col-md-3 col-4">
                        <div className="client-logo text-end">
                          <img
                            src="img/clients/html.png"
                            className="img-fluid"
                            alt=""
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>

            <Footer className="section" />

           
          </VerticalScrollElementLayout>
        );
      }}
    />
  );
}
